### ISSUE TITLE
Wordpress plugin installation

### ISSUE THREAD

**Issue by Kenworld** [Flutterwave/rave-woocommerce#16]
i get the error Abort class-pclzip.php : Missing zlib extensions when i try installing

**Comment by bajoski34** [comment]
Hi @Kenworld  this error  is related to the PHP installation on the hosting server that you are using. kindly ask your hosting provider to update your PHP version.

you can also make use of the link below for possible solutions the problem:
https://forum.infinityfree.net/t/installation-failed-abort-class-pclzip-php-missing-zlib-extensions/33187

Best Regards
