### ISSUE TITLE
Webhook doesn't work on prod environment 

### ISSUE THREAD

**Issue by ernestkamara** [Flutterwave/rave-woocommerce#17]
I installed this plugin and tested to work on our dev and test environments, but not on prod.

We are using [Pantheon](pantheon.io) for deployment and works great for us so far. 

Pantheon creates a platform domain for all our environments, i.e.
```
https://dev-gofenam-marketplace-salone.pantheonsite.io/
https://test-gofenam-marketplace-salone.pantheonsite.io/
https://live-gofenam-marketplace-salone.pantheonsite.io/
```
Generated webhook on the different  environments are:
```
https://dev-gofenam-marketplace-salone.pantheonsite.io/wc-api/Flw_WC_Payment_Webhook/
https://test-gofenam-marketplace-salone.pantheonsite.io/wc-api/Flw_WC_Payment_Webhook/
https://live-gofenam-marketplace-salone.pantheonsite.io/wc-api/Flw_WC_Payment_Webhook/

```
However, redirecting from a successful payment(sandbox) in prod(www.gofenam.com) shows the following:

> “There has been a critical error on your website. Please check your site admin email inbox for instructions.
> Learn more about debugging in WordPress.”
> 

Webhook URL on Flutterwave Dashboard:
`https://live-gofenam-marketplace-salone.pantheonsite.io/wc-api/Flw_WC_Payment_Webhook/
`
We also tried using `https://www.gofenam.com/wc-api/Flw_WC_Payment_Webhook/` but doesn’t resolve the issue. Anything wrong we are doing?

Thanks in advance.

**Comment by bajoski34** [comment]
Hi @ernestkamara  the solution to this issue is to simply check the disable logging option on the rave woo-commerce setting page and the error should disappear.

image reference - https://www.screencast.com/t/1i2W3c2PG
