### ISSUE TITLE
How do integrate a sub-account ID for split payments Woo-commerce wordpress

### ISSUE THREAD

**Issue by gilbertmpanga12** [Flutterwave/rave-woocommerce#18]
I have searched for sub-accounts integration for the woo-commerce plugin but couldn't find any configuration for it.

**Comment by bajoski34** [comment]
HI @gilbertmpanga12 please kindly use the up-to-date plugin( 2.2.6 ) to  utilize the subaccount feature. Read the instruction in the readme file.

Best regards
