### ISSUE TITLE
A question/feature request regarding recurring payments

### ISSUE THREAD

**Issue by AmibeWebsites** [Flutterwave/rave-woocommerce#6]
Hi, I've set up recurring payment plans in the Rave dashboard but how do I connect these to products in the WooCommerce basket?

For example, Monthly Subscription is a product in WooCommerce that should be billed month.

Thank you.

**Comment by temiadesina** [comment]
Hi @AmibeWebsites 

Great news, we would be launching recurring payments on the woocommerce plugin. 
https://github.com/Flutterwave/rave-woocommerce/pull/9

You would now be able to use your Woocommerce recurring plugin with our payment plugin. The update should go live by Monday the 15th of April.

**Comment by AmibeWebsites** [comment]
Wonderful @temiadesina, thank you. I'll take a look when it's live and test it out...
